### ISSUE TITLE
Process `.gitrobrc` with ERB first

### ISSUE THREAD

**Issue by mikeatlas** [michenriksen/gitrob#41]
I have dynamic parameters from using a separate postgres db in another docker-composed container, for example:

``` yaml

---
sql_connection_uri: postgres://gitrob:password@<%= DB_GITROB_PORT_5432_TCP_ADDR %>:5432/gitrob
github_access_tokens:
- blablabla
```

The code change needed would be from http://stackoverflow.com/a/25862188/101827 

``` ruby
template = ERB.new File.new("path/to/config.yml.erb").read
processed = YAML.load template.result(binding)
```

located: https://github.com/michenriksen/gitrob/blob/master/lib/gitrob.rb#L98-L100

I can make a PR for this but in the meantime I'll just run a wrapper script to pre-process my `.rcfile` before running gitrob.
